### ISSUE TITLE
wishlist: help command should show default values

### ISSUE THREAD

**Issue by chrishiestand** [CleverCloud/cliparse-node#13]
It would be great if the help command automatically displayed default values.

**Comment by chrishiestand** [comment]
I might be able to send a PR for this.

**Comment by divarvel** [comment]
Hi, I can do it. Do you have an example of the desired output?

**Comment by chrishiestand** [comment]
Sorry I haven't submitted PR yet, I just haven't found the time. What I had in mind was something like python's argparse https://docs.python.org/3/library/argparse.html. So if you have these options:

```
cliparse.option("redis_host", { aliases: ["h"], description: "redis host or ip", default: "localhost" }),
cliparse.option("redis_port", { aliases: ["p"], description: "redis port number", default: 6379 })],
```

Then the usage would look something like:

```
...
[--redis_host, -h]       redis host or ip (default: localhost)
[--redis_port, -p]       redis port number (default: 6379)
```

The output can be just JSON.stringify(my_default) so that arrays and objects can be shown as well.

But I'm not especially attached to any particular style. Whatever looks clean sounds good to me.

**Comment by divarvel** [comment]
chrishiestand that should be ok now.

I display default: false for flags as well, maybe this could be hidden.

**Comment by chrishiestand** [comment]
I've checked out this branch and it seems to work. Thank you!

Yes, I think you're probably right, flag defaults (which are false) should be hidden. But I'd still consider this commit worth merging.
