### ISSUE TITLE
Ownership transfer to Clever Cloud

### ISSUE THREAD

**Issue by divarvel** [CleverCloud/cliparse-node#24]
I have created this library as part of my job at Clever Cloud. Since I've left the company and I don't use cliparse anymore, the Clever Cloud team and I have decided to transfer ownership.

I'll transfer ownership of the npm package to clever cloud, and will shut down this repo and add a note redirecting to its Clever Cloud clone (I can't directly transfer its ownership to the CleverCloud organization because I can't create repos in it).

**Comment by judu** [comment]
I just forked the repository in https://github.com/CleverCloud/cliparse-node

**Comment by judu** [comment]
Is there a way to transfer once the fork has been made?

**Comment by judu** [comment]
Btw, we have a clevercloud npm organisation. I'm not sure how I can provide a proper link to it…

**Comment by divarvel** [comment]
I can't add an organization as a maintainer. I've added all the maintainers
from uuid-to-pokemon.
